version: '3.8'
services:
  telegram-gpt:
    build:
      context: ./
    image: telegram-gpt:latest
    container_name: 'telegram-gpt'
    environment:
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ADMIN_TELEGRAM_ID: ${ADMIN_TELEGRAM_ID}
